# Generated by Django 5.1.4 on 2024-12-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduwize_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='profile_pictures/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='eduwize_app.student')),
            ],
        ),
    ]
