# Generated by Django 5.2 on 2025-05-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduwize_app', '0002_studentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='is_helpful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_messages', to='eduwize_app.student'),
        ),
    ]
