# Generated by Django 5.2 on 2025-05-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduwize_app', '0003_aichatbot_feedback_aichatbot_is_helpful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('exam_paper', 'Exam Paper')], default='video', max_length=10),
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='exam_papers/')),
                ('year', models.PositiveIntegerField(help_text='The year of the exam paper (e.g., 2023)')),
                ('exam_type', models.CharField(help_text='Type of exam (e.g., Midterm, Final, Mock)', max_length=50)),
                ('level', models.CharField(choices=[('NQF2', 'NQF Level 2'), ('NQF3', 'NQF Level 3'), ('NQF4', 'NQF Level 4')], help_text='The study level this exam paper is for', max_length=5)),
                ('is_solution', models.BooleanField(default=False, help_text='Is this a solution paper?')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='eduwize_app.course')),
                ('related_paper', models.ForeignKey(blank=True, help_text='If this is a solution, link to the original paper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='eduwize_app.exampaper')),
            ],
            options={
                'verbose_name': 'Exam Paper',
                'verbose_name_plural': 'Exam Papers',
                'ordering': ['-year', 'exam_type'],
            },
        ),
    ]
